language: elixir
sudo: false # to use faster container based build environment

matrix:
  include:
    - otp_release: 18.3
      elixir: 1.1.1
    - otp_release: 18.3
      elixir: 1.2.6
    - otp_release: 18.3
      elixir: 1.3.4
    - otp_release: 19.0
      elixir: 1.3.4

after_script:
  - mix deps.get
  - MIX_ENV=dev mix credo
  - MIX_ENV=docs mix docs # generate docs to check if it is not breaking.
  - MIX_ENV=test mix coveralls.travis 
  
