language: elixir

elixir:
  - 1.0.5
  - 1.1.1
  - 1.2.0

otp_release:
  - 17.3
  - 18.1

sudo: false # to use faster container based build environment

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix docs # generate docs to check if it is not breaking.
  
matrix:
  exclude:
    - otp_release: 17.3 # exclude elixir 1.2 from running in incompatible versions
      elixir: 1.2.0
