sudo: false # to use faster container based build environment
language: elixir
elixir:
  - 1.0.5
  - 1.1.0
  - 1.2.0
otp_release:
  - 18.1
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix docs # generate docs to check if it is not breaking.
