language: elixir
sudo: false # to use faster container based build environment

matrix:
  include:
    - otp_release: 18.3
      elixir: 1.4.5
    - otp_release: 19.0
      elixir: 1.4.5
    - otp_release: 20.0
      elixir: 1.4.5
    - otp_release: 19.0
      elixir: 1.5.1
    - otp_release: 20.0
      elixir: 1.5.1

after_script:
  - mix deps.get
  - MIX_ENV=dev mix credo
  - mix docs # generate docs to check if it is not breaking.
  - MIX_ENV=test mix coveralls.travis 
  
