language: elixir
sudo: false

matrix:
  include:
    - otp_release: 19.3
      elixir: 1.5.3
    - otp_release: 19.3
      elixir: 1.6.6
    - otp_release: 20.3
      elixir: 1.6.6
    - otp_release: 21.1
      elixir: 1.7.4

script:
  - mix credo --strict
  - MIX_ENV=test mix coveralls.travis --trace --cover

